apiVersion: v1
kind: Pod
metadata:
  name: session-service
  #namespace: local-player-session
spec:
  containers:
  - name: session-service
    image: harbor-sandbox.obinfra.net/sandbox/play/session-service:latest
    env:
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:informix-sqli://database-cust:9088/cust"